### ISSUE TITLE
dbconfig error

### ISSUE THREAD

**Issue by chrishough** [jalkoby/squasher#10]
```
➜  API git:(feature-api-251-squash-migrations) squasher 2015
(erb):26:in `dbconfig': uninitialized constant Squasher::Config::Rails (NameError)
	from /Users/chrishough/.rbenv/versions/2.2.0/lib/ruby/2.2.0/erb.rb:863:in `eval'
	from /Users/chrishough/.rbenv/versions/2.2.0/lib/ruby/2.2.0/erb.rb:863:in `result'
	from /Users/chrishough/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/squasher-0.1.4/lib/squasher/config.rb:70:in `dbconfig'
	from /Users/chrishough/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/squasher-0.1.4/lib/squasher/config.rb:28:in `dbconfig?'
	from /Users/chrishough/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/squasher-0.1.4/lib/squasher/worker.rb:38:in `check!'
	from /Users/chrishough/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/squasher-0.1.4/lib/squasher/worker.rb:16:in `process'
	from /Users/chrishough/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/squasher-0.1.4/lib/squasher/worker.rb:8:in `process'
	from /Users/chrishough/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/squasher-0.1.4/lib/squasher.rb:12:in `squash'
	from /Users/chrishough/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/squasher-0.1.4/bin/squasher:6:in `<top (required)>'
	from /Users/chrishough/.rbenv/versions/2.2.0/bin/squasher:23:in `load'
```

Thoughts on how to fix this?

**Comment by jalkoby** [comment]
Hi, it looks like that in your database config there is an interpolation with a rails variables. Squasher doesn't preload your app, as the result a processing of your config file breaks the process. 
To solve the issue for the moment of squasher usage make the `database.yml` a plain yml file(without any <% %> block). After you've finished you can revert your dynamic database config.

**Comment by chrishough** [comment]
Yes, we do that, bummer, because those values are in the secrets file!  Instead of adjusting that, we ended up manually creating the squashed migration off the current schema.  

It seems a bit odd that these are required to be set instead of using secrets in rails 4.
