### ISSUE TITLE
squasher doesn't revert database connection config after use

### ISSUE THREAD

**Issue by chenwardT** [jalkoby/squasher#11]
I just squashed all my migrations w/o error, but upon opening a rails console and calling a model method I get the following:

[1] pry(main)> SomeModel.count
ActiveRecord::NoDatabaseError: FATAL:  database "squasher" does not exist
from /home/chen/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `rescue in connect'

Sure enough, it looks like the connection_config has been changed:

SomeModel.connection_config
=> {:adapter=>"postgresql",
 :encoding=>"unicode",
 :pool=>5,
 :timeout=>5000,
 :username=>"some_username",
 :password=>"some_password",
 :database=>"squasher"}

I'm running a full text search of "squasher" of my system now to find out where this is being read in from, as the string isn't being found within my project folder. Any help would be appreciated.

**Edit**: If it matters, I declined persisting of the tmp database during the squash operation.

**Comment by chenwardT** [comment]
Ah, looks like it was the same thing as https://github.com/jalkoby/squasher/issues/8. Resolved.

**Comment by jalkoby** [comment]
you are welcome

**Comment by DannyBen** [comment]
This is not resolved for me.

After running squasher, the console breaks. I am not using spring. I also declined the tmp database (and there is an empty squasher file created in my app dir whenever I run db migrate, not sure if its related).

**Comment by jalkoby** [comment]
@DannyBen can you post the error trace log? it will help to figure out what's going on

**Comment by DannyBen** [comment]
Dont have the trace, I rebooted the termnal....
I am not even sure its the exact same error - but I saw two issues regarding the console breaking, I figured I would piggy back on one of them instead of opening a new one.

When I tried accessing any model data in the console, I got a "table does not exist" error.

**Comment by jalkoby** [comment]
well, I cannot help you without this information. You need to repeat the steps and provide the output

**Comment by DannyBen** [comment]
Well - the good news, is that it is reproducible.

Here is the trace after running `squasher 2016`, choosing "no" to keep tmp and "no" to clean old migrations.

In any case - I thought I was helping you find bugs in your gem. I do not need help with it, as I will probably go back to manually squashing my schema.rb into a clean migration and be done with it, so if you are not bothered by these errors, neither am I.

```
> rails runner "ap Task.first"
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `initialize': SQLite3::SQLException: no such table: tasks: SELECT  "tasks".* FROM "tasks"  ORDER BY "tasks"."id" ASC LIMIT 1 (ActiveRecord::StatementInvalid)
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `new'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `prepare'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/sqlite3_adapter.rb:296:in `block in exec_query'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/query_diet-0.5.3/lib/query_diet/active_record_ext.rb:5:in `block in log_with_query_diet'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/query_diet-0.5.3/lib/query_diet/logger.rb:18:in `block in log'
from /home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/query_diet-0.5.3/lib/query_diet/logger.rb:17:in `log'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/query_diet-0.5.3/lib/query_diet/active_record_ext.rb:4:in `log_with_query_diet'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/sqlite3_adapter.rb:293:in `exec_query'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:351:in `select'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/querying.rb:39:in `find_by_sql'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation.rb:638:in `exec_queries'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation.rb:514:in `load'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation.rb:243:in `to_a'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/bullet-4.14.7/lib/bullet/active_record42.rb:29:in `to_a'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:500:in `find_nth_with_limit'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:484:in `find_nth'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:127:in `first'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/querying.rb:3:in `first'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/runner.rb:62:in `<top (required)>'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/runner.rb:62:in `eval'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/runner.rb:62:in `<top (required)>'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:90:in `runner'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
from /vagrant/rails/secsys/bin/rails:8:in `<top (required)>'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
from /home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from -e:1:in `<main>'
```

**Comment by jalkoby** [comment]
It seems squasher doesn't work well with sqlite database. to be honest it has not been tested with this RDBS, so it probably killed your dev database. As the result, I guess it's better to create an issue about `squasher + sqlite`
