### ISSUE TITLE
Rails 5.0 issue with ActiveRecord::NoEnvironmentInSchemaError

### ISSUE THREAD

**Issue by tadiou** [jalkoby/squasher#27]
Related to: https://github.com/rails/rails/issues/23279

When trying to open a new tmp database during the squasher process, it errors out with this error that was reported in the rails ticket above.

I tried breaking apart the process between `db:drop` & `db:create` with `bin/rails db:environment:set RAILS_ENV=development` as it recommends, but that didn't solve anything.

I'll try to take a further look and if I can solve it, get a PR for you.

**Comment by jalkoby** [comment]
Thank you for reporting the problem with rails 5.0. It would be nice if you will follow the issue and make a change (if needed) in the end

**Comment by logicminds** [comment]
I am getting this error as well.  I don't see the ar_metadata table in my schema file.  It was there at one time but I think it was removed somehow.  However, it still existing on the database server.

**Comment by logicminds** [comment]
Output when trying to drop my db.


```ruby
 heroku run 'bin/rails db:environment:set RAILS_ENV=stage && rails db:drop' -r stage
Running bin/rails db:environment:set RAILS_ENV=stage && rails db:drop on ⬢ staging... up, run.4473
  ActiveRecord::InternalMetadata Load (2.1ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", nil], ["LIMIT", 1]]
   (0.9ms)  BEGIN
  SQL (1.2ms)  INSERT INTO "ar_internal_metadata" ("value", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "key"  [["value", "stage"], ["created_at", 2016-08-19 17:41:26 UTC], ["updated_at", 2016-08-19 17:41:26 UTC]]
   (2.2ms)  COMMIT
  ActiveRecord::SchemaMigration Load (19.2ms)  SELECT "schema_migrations".* FROM "schema_migrations"
   (27.6ms)  SELECT "ar_internal_metadata"."value" FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1  [["key", nil]]
rails aborted!
ActiveRecord::NoEnvironmentInSchemaError:

Environment data not found in the schema. To resolve this issue, run:

	bin/rails db:environment:set RAILS_ENV=stage

/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1256:in `last_stored_environment'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:48:in `check_protected_environments!'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:11:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/app/bin/rails:5:in `require'
/app/bin/rails:5:in `<main>'
Tasks: TOP => db:drop => db:check_protected_environments
(See full trace by running task with --trace)
```

**Comment by logicminds** [comment]
Is this needed anymore?  What magic is rails doing?

```ruby
create_table "ar_internal_metadata", primary_key: "key", force: :cascade do |t|
      t.string   "value"
      t.datetime "created_at", null: false
      t.datetime "updated_at", null: false
    end
```

**Comment by n-rodriguez** [comment]
> Is this needed anymore? What magic is rails doing?

http://blog.bigbinary.com/2016/06/07/rails-5-prevents-destructive-action-on-production-db.html

**Comment by thewoolleyman** [comment]
Prepend `DISABLE_DATABASE_ENVIRONMENT_CHECK=1` to the `squasher` command and it'll work.

I'm [trying to get rails to document this better](https://github.com/rails/rails/issues/27971)

**Comment by jalkoby** [comment]
Sorry, guys, for very long response - the new version is release. Enjoy squasher with a cutting edge rails

**Comment by poombavai** [comment]
Having the same problem. How to solve this?

**Comment by jalkoby** [comment]
Please update squasher to 0.3.0
