### ISSUE TITLE
Does not work with ENV in database.yml

### ISSUE THREAD

**Issue by trigun0x2** [jalkoby/squasher#30]
Tested with Rails 5.0.0

**Comment by jalkoby** [comment]
@trigun0x2 can you share your file, to make a test?

**Comment by trigun0x2** [comment]
https://gist.github.com/4aab2b04649338ea5be465495e6de58f

It couldn't find the DB then I replaced it all with the DB_URL and it worked fine.

**Comment by jalkoby** [comment]
hmm, it's strange. Can you tell me what value or at least format was in DB_NAME ?

**Comment by trigun0x2** [comment]
Here's the .env:

```
# DB
DB_URL="postgresql://namename:pwd@postgres:5432/namename?encoding=utf8&pool=5&timeout=5000"
#url: "postgresql://namename:pwd@localhost:5432/namename?encoding=utf8&pool=5&timeout=5000"
DB_HOST="localhost"
DB_NAME="namename"
DB_USER="namename"
DB_PWD="pwd"
```

**Comment by jalkoby** [comment]
probably, squasher didn't create `squasher` database as  DB_USER doesn't have a permission to do it

**Comment by trigun0x2** [comment]
Well the DB_URL has the exact same credentials and it worked fine.

**Comment by jalkoby** [comment]
I have no idea for that moment. Could you revert the settings and provide the error log?

**Comment by trigun0x2** [comment]
```
Squasher is creating a tmp database
rake aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/pgsql_socket/.s.PGSQL.5432"?
/Users/nemo/Documents/projects/bob-api/app/models/user.rb:37:in `include'
/Users/nemo/Documents/projects/bob-api/app/models/user.rb:37:in `<class:User>'
/Users/nemo/Documents/projects/bob-api/app/models/user.rb:32:in `<top (required)>'
/Users/nemo/Documents/projects/bob-api/config/routes.rb:3:in `block in <top (required)>'
/Users/nemo/Documents/projects/bob-api/config/routes.rb:1:in `<top (required)>'
/Users/nemo/Documents/projects/bob-api/config/environment.rb:5:in `<top (required)>'
/Users/nemo/.rbenv/versions/2.3.0/bin/bundle:23:in `load'
/Users/nemo/.rbenv/versions/2.3.0/bin/bundle:23:in `<main>'
Tasks: TOP => db:drop => db:check_protected_environments => environment
(See full trace by running task with --trace)
```

Does seem like it's not able to create the db.. :/
