### ISSUE TITLE
Squasher failing on a Rails 5.1.3 app.

### ISSUE THREAD

**Issue by marvindanig** [jalkoby/squasher#41]
`$ squasher clean`

Squasher is applying the clean migration
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

```
  class SquasherClean < ActiveRecord::Migration[4.2]
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:525:in `inherited'
/Users/admin/projects/RoR/bubblin/db/migrate/20170901171409_squasher_clean.rb:1:in `<top (required)>'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:962:in `load_migration'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:958:in `migration'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:953:in `disable_ddl_transaction'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:1305:in `use_transaction?'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:1297:in `ddl_transaction'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:1200:in `each'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:1148:in `block in migrate'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:1148:in `migrate'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:1007:in `up'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:985:in `migrate'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/admin/projects/RoR/bubblin/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/admin/.rbenv/versions/2.4.1/bin/bundle:23:in `load'
/Users/admin/.rbenv/versions/2.4.1/bin/bundle:23:in `<main>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
```

**Comment by jalkoby** [comment]
Please upgrade to v0.5.0  and run clean like

```bash
squasher clean -m 5.1
```

**Comment by jalkoby** [comment]
please read the readme. The clean is not what you looking for. Just run:
```bash
squasher -m 5.1 2017
```
Clean creates a migration for cleaning your database, not your migrations

**Comment by danielricecodes** [comment]
Thanks - but this should definitely be mentioned in the README too! 
 https://github.com/jalkoby/squasher#usage
