### ISSUE TITLE
Can't run on sql mode - No such file or directory db/structure.sql

### ISSUE THREAD

**Issue by JoaoFagundes** [jalkoby/squasher#65]
similar to  #52 which was closed with no further details, but I do have a `structure.sql` file in the db folder 
```
Traceback (most recent call last):
	21: from /home/fagundes/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:22:in `<main>'
	20: from /home/fagundes/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:22:in `eval'
	19: from /home/fagundes/.rvm/gems/ruby-2.6.1/bin/squasher:23:in `<main>'
	18: from /home/fagundes/.rvm/gems/ruby-2.6.1/bin/squasher:23:in `load'
	17: from /home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/bin/squasher:41:in `<top (required)>'
	16: from /home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/lib/squasher.rb:21:in `squash'
	15: from /home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/lib/squasher/worker.rb:8:in `process'
	14: from /home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/lib/squasher/worker.rb:18:in `process'
	13: from /home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/lib/squasher/worker.rb:68:in `under_squash_env'
	12: from /home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/lib/squasher/config.rb:99:in `stub_dbconfig'
	11: from /home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/lib/squasher/worker.rb:77:in `block in under_squash_env'
	10: from /home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/lib/squasher/worker.rb:24:in `block in process'
	 9: from /home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/lib/squasher/worker.rb:24:in `open'
	 8: from /home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/lib/squasher/worker.rb:24:in `block (2 levels) in process'
	 7: from /home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/lib/squasher/render.rb:6:in `render'
	 6: from /home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/lib/squasher/render.rb:17:in `render'
	 5: from /home/fagundes/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/erb.rb:901:in `result'
	 4: from /home/fagundes/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/erb.rb:901:in `eval'
	 3: from (erb):3:in `render'
	 2: from /home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/lib/squasher/render.rb:21:in `each_schema_line'
	 1: from /home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/lib/squasher/render.rb:21:in `open'
/home/fagundes/.rvm/gems/ruby-2.6.1/gems/squasher-0.6.2/lib/squasher/render.rb:21:in `initialize': No such file or directory @ rb_sysopen - /home/fagundes/Documents/code/db/structure.sql (Errno::ENOENT)
  
$ ls /home/fagundes/Documents/code/db/structure.sql                                                                          
/home/fagundes/Documents/code/db/structure.sql
```

command ran was `squasher 2021/3/11 -s`

**Comment by JoaoFagundes** [comment]
following suggestions on #52 about the renaming of the schema file to `name.sq` i did a local monkey patch to avoid this renaming when the sql option is run, and it worked, but I must confess I couldn't understand properly what that line is actually doing by renaming the file and why it isn't broken for active records schemas as well?
